### ISSUE TITLE
Undefined variable on load errors...

### ISSUE THREAD

**Issue by xtiansimon** [tomtom/tskeleton_vim#12]
I've just reinstalled `tskeleton` using Vundle, hoping to get my copy of vim up to date with all the yummy plugins (uninstall was just .bak-ing the plugin dir, hope that's ok). So far, so good with many plugins using Vundle: however, **tSkeleton** (with tlib) is not loading properly on lines 3,4,7,8:
```
E121: Undefined variable: g:tlib_filename_sep
E116: Invalid arguments for function join(a:filename_parts, g:tlib_filename_sep)
E15: Invalid expression: join(a:filename_parts, g:tlib_filename_sep)
Press ENTER or type command to continue
```
Any idea what this could mean?

---- 
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 16 2015 07:43:00)
Included patches: 1-663
Compiled by Arch Linux
Huge version without GUI. [...]
[... lots of stuff...]
```

**Comment by tomtom** [comment]
> |E121: Undefined variable: g:tlib_filename_sep|

Did you also reinstall tlib? The variable was renamed to g:tlib#dir#sep 
and I assume that the error results from using an outdated version of tlib.

Did you install tlib & tskeleton from the original 
https://github.com/tomtom/*_vim repos or from another source?

**Comment by xtiansimon** [comment]
I'm migrating my plugin management to Vundle and I used:
```
:Plugin 'tomtom/tlib_vim'
:Plugin 'tomtom/tskeleton_vim'
```
If the outdated tlib is being called, then I missed deleting something. Where are the usual places where tlib plugin files are stored?

**Comment by tomtom** [comment]
> If the outdated tlib is being called, then I missed deleting 
> something. Where are the usual places where tlib plugin files are stored? 
Either plugin/02tlib.vim or autoload/tlib/*.

HTH

**Comment by xtiansimon** [comment]
Thanks. Found the issues in autoload. I use vim nearly every day, and I didn't want to break it by being too aggressive.
