### ISSUE TITLE
Unknown function: tskeleton#IncreaseRevisionNumber

### ISSUE THREAD

**Issue by tolecnal** [tomtom/tskeleton_vim#13]
Quite some time back, I started to get the following error message.

Error detected while processing BufWrite Auto commands for "*":
E117: Unknown function: tskeleton#IncreaseRevisionNumber

It's not too often I work with files with revision numbers, so I temporarily disabled the BufWrite hook, but lately I've worked on files that do require revision updates which lead me to debug the error. I can't see the function defined in any of the files for the script, nor in the dependency tlib.

Has this function been removed, or am I missing something?

The configuration in my vimrc is as follows:
autocmd BufWritePre * call tskeleton#IncreaseRevisionNumber()

**Comment by tomtom** [comment]
> Error detected while processing BufWrite Auto commands for "*":
>
> E117: Unknown function: tskeleton#IncreaseRevisionNumber
>

Since it had nothing to do with templates, I moved the function to 
https://github.com/tomtom/tversions_vim

**Comment by tolecnal** [comment]
Ah, that would indeed explain it. Thanks for the feedback.
